routes/web.php
<?php

use App\Http\Controllers\CardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->name('dashboard');

Route::resource('user', UserController::class)->middleware(['permission:management.user']);

Route::resource('category', CategoryController::class);
Route::resource('product', ProductController::class);


//CART
Route::get('/card/index', [CardController::class, 'index'])->name('cart');
Route::get('/addtocard/{product}', [CardController::class, 'addToCard'])->middleware(['auth'])->name('addToCard');
Route::get('/removefromcard/{product}', [CardController::class, 'removeFromCard'])->middleware(['auth'])->name('removeFromCard');


Route::get('/mediadelete/{media?}', function (Media $media) {
    $media->delete();
    return redirect()->back();
})->middleware(['permission:management.user'])->name('mediadelete');

require __DIR__ . '/auth.php';

app/Models/Product.php
<?php

namespace App\Models;

use Spatie\MediaLibrary\HasMedia;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Builder;
use Spatie\MediaLibrary\InteractsWithMedia;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Product extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia;

    protected $fillable = ['name', 'category_id', 'content', 'price'];
    protected $appends = ['image', 'images'];

    public function getImagesAttribute()
    {
        return $this->getMedia('images');
    }
    public function getImageAttribute()
    {
        return $this->getFirstMediaUrl('images');
    }

    public function scopeOfCategory(Builder $query, ?Category $cat = null): Builder
    {
        return $query->when($cat, function ($query) use ($cat) {
            $query->where('category_id', $cat->id);
        });
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;

class ProductController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $category = null;

        if ($request->get('category'))
            $category = Category::findOrFail($request->get('category'));

        $products = Product::when($category, function ($query) use ($category) {
            $query->ofCategory($category);
        })->paginate()->appends(['category' => $category?->id]);

        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $user = $request->user();
        if (!$user->can('management.content'))
            return abort(403, 'USER DOES NOT HAVE THE RIGHT PERMISSIONS.');

        $product = new Product();
        $categories = Category::all();
        return view('product.form', compact('product', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StoreProductRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $user = $request->user();
        if (!$user->can('management.content'))
            return abort(403, 'USER DOES NOT HAVE THE RIGHT PERMISSIONS.');

        $data = $request->validated();

        $product = Product::create($data);

        if ($request->hasFile('images')) {
            $product->addMultipleMediaFromRequest(['images'])
                ->each(function ($file) {
                    $file->toMediaCollection('images');
                });
        }

        return redirect()->route('product.index')->with('success', __('Product Created Succesfuly.'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Product $product)
    {
        $user = $request->user();
        if (!$user->can('management.content'))
            return abort(403, 'USER DOES NOT HAVE THE RIGHT PERMISSIONS.');

        $categories = Category::all();
        return view('product.form', compact('product', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdateProductRequest  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, Product $product)
    {
        $user = $request->user();
        if (!$user->can('management.content'))
            return abort(403, 'USER DOES NOT HAVE THE RIGHT PERMISSIONS.');

        $data = $request->validated();
        $product->update($data);

        if ($request->hasFile('images')) {
            $product->addMultipleMediaFromRequest(['images'])
                ->each(function ($file) {
                    $file->toMediaCollection('images');
                });
        }
        return redirect()->route('product.index')->with('success', __('Product Updated Succesfuly.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();

        return redirect()->route('product.index')->with('success', __('Product Deleted Succesfuly.'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/product/form.blade.php
@php($title = $product->exists ? __('Edit Product') : __('New Product'))
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ $title }}
        </h2>
    </x-slot>

    <form method="post" enctype="multipart/form-data"
        action="{{ $product->exists ? route('product.update', $product) : route('product.store') }}">
        @csrf
        @if ($product->exists)
            @method('PUT')
        @endif
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <label for="images">{{ __('Images') }}</label>
                        <div class="input-group mb-3">
                            <div class="custom-file">
                                <input id="images" name="images[]" type="file" class="custom-file-input"
                                    id="inputGroupFile01" multiple>
                                <label
                                    class="form-control-custom @error('images') is-invalid @enderror custom-file-label"
                                    for="inputGroupFile01">
                                </label>
                            </div>
                        </div>
                        @error('images')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>

                    @if ($product->exists)
                        <div class="col-md-12">
                            <label>{{ __('Images') }}</label>
                            <div class="form-group">
                                @foreach ($product->getMedia('images') as $image)
                                    <a href="{{ route('mediadelete', $image) }}">
                                        <img src="{{ $image->getUrl() }}" width="70" height="70">
                                    </a>
                                @endforeach
                            </div>
                        </div>
                    @endif

                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="name">{{ __('Name') }}</label>
                            <input id="name" type="text"
                                class="form-control @error('name') is-invalid @enderror" name="name"
                                value="{{ $product->name }}" required autocomplete="name" autofocus>

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="price">{{ __('Price') }}</label>
                            <input id="name" type="number"
                                class="form-control @error('price') is-invalid @enderror" name="price"
                                value="{{ $product->exists ? $product->price : 0 }}" required>

                            @error('price')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>

                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="category_id">{{ __('Category') }}</label>
                            <select id="category_id" class="form-control @error('category_id') is-invalid @enderror"
                                name="category_id">
                                <option value="">-</option>
                                @foreach ($categories as $category)
                                    <option value="{{ $category->id }}"
                                        {{ $product->category_id == $category->id ? 'selected' : '' }}>
                                        {{ $category->name }}
                                    </option>
                                @endforeach
                            </select>

                            @error('category')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="content">{{ __('Content') }}</label>
                            <textarea class="form-control @error('content') is-invalid @enderror" id="content" name="content" rows="3">{{ $product->content }}</textarea>

                            @error('content')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i>
                    {{ __('Save') }}
                </button>
            </div>
        </div>
    </form>
</x-app-layout>

resources/views/product/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Products') }}
            @can('management.content')
                <a href="{{ route('product.create') }}" class="btn btn-sm btn-primary float-right">
                    <i class="fas fa-plus"></i>
                    {{ __('Create Product') }}
                </a>
            @endcan
        </h2>
    </x-slot>
    <div class="card">
        <div class="table-responsive">
            <table class="table table-hover">

                <thead class="thead-dark">
                    <tr>
                        <th>{{ __('Image') }}</th>
                        <th>{{ __('Name') }}</th>
                        <th>{{ __('Price') }}</th>
                        <th class="text-right">{{ __('Actions') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($products as $product)
                        <tr>
                            <td><img src="{{ $product->image }}" alt="" style="height: 75px;"></td>
                            <td>{{ $product->name }}</td>
                            <td>{{ $product->price }}</td>

                            <td class="text-right">
                                <a href="{{ route('addToCard', $product) }}" class="btn btn-info"><i
                                        class="fas fa-plus"></i>{{ __('Add To Card') }}</a>
                                @can('management.content')
                                    <a href="{{ route('product.edit', $product) }}" class="btn btn-primary"><i
                                            class="fas fa-pen"></i></a>
                                    <form action="{{ route('product.destroy', $product) }}" method="POST"
                                        class="d-inline-block" onsubmit="return confirm('{{ __('Are you sure?') }}');">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-danger">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </form>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
</x-app-layout>