routes/web.php
<?php

use App\Http\Controllers\CardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->name('dashboard');

Route::resource('user', UserController::class)->middleware(['permission:management.user']);

Route::resource('category', CategoryController::class);
Route::resource('product', ProductController::class);


//CART
Route::get('/card/index', [CardController::class, 'index'])->name('cart');
Route::get('/addtocard/{product}', [CardController::class, 'addToCard'])->middleware(['auth'])->name('addToCard');
Route::get('/removefromcard/{product}', [CardController::class, 'removeFromCard'])->middleware(['auth'])->name('removeFromCard');


Route::get('/mediadelete/{media?}', function (Media $media) {
    $media->delete();
    return redirect()->back();
})->middleware(['permission:management.user'])->name('mediadelete');

require __DIR__ . '/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Category extends Model
{
    use HasFactory;

    public $fillable = ['name'];

    public function product(): HasMany
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate();

        return view('category.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {

        $user = $request->user();

        if (!$user->can('management.content'))
            return abort(403, 'USER DOES NOT HAVE THE RIGHT PERMISSIONS.');

        $category = new Category();
        return view('category.form', compact('category'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $user = $request->user();

        if (!$user->can('management.content'))
            return abort(403, 'USER DOES NOT HAVE THE RIGHT PERMISSIONS.');

        $data = $request->validated();
        $category = Category::create($data);

        return redirect()->route('category.index')->with('success', __('Category Created Succesfuly.'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Category $category)
    {
        $user = $request->user();

        if (!$user->can('management.content'))
            return abort(403, 'USER DOES NOT HAVE THE RIGHT PERMISSIONS.');
        return view('category.form', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, Category $category)
    {
        $user = $request->user();

        if (!$user->can('management.content'))
            return abort(403, 'USER DOES NOT HAVE THE RIGHT PERMISSIONS.');

        $data = $request->validated();
        $category->update($data);

        return redirect()->route('category.index')->with('success', __('Category Updated Succesfuly.'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if ($category->product()->exists())
            return redirect()->route('category.index')->with('warning', __('First you need to remove product(s) of the category.'));
        $category->delete();

        return redirect()->route('category.index')->with('success', __('Category Deleted Succesfuly.'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/category/form.blade.php
@php($title = $category->exists ? __('Edit Category') : __('New Category'))
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ $title }}
        </h2>
    </x-slot>

    <form method="post" enctype="multipart/form-data"
        action="{{ $category->exists ? route('category.update', $category) : route('category.store') }}">
        @csrf
        @if ($category->exists)
            @method('PUT')
        @endif
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="name">{{ __('Name') }}</label>
                            <input id="name" type="text"
                                class="form-control @error('name') is-invalid @enderror" name="name"
                                value="{{ $category->name }}" required autocomplete="name" autofocus>

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i>
                    {{ __('Save') }}
                </button>
            </div>
        </div>
    </form>
</x-app-layout>

resources/views/category/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4   font-weight-bold">
            {{ __('Categories') }}
            @can('management.content')
                <a href="{{ route('category.create') }}" class="btn btn-sm btn-primary float-right">
                    <i class="fas fa-plus"></i>
                    {{ __('Create Category') }}
                </a>
            @endcan
        </h2>
    </x-slot>
    <div class="card">
        <div class="table-responsive">
            <table class="table table-hover">

                <thead class="thead-dark">
                    <tr>
                        <th>{{ __('Name') }}</th>
                        <th class="text-right">{{ __('Actions') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>{{ $category->name }}</td>

                            <td class="text-right">
                                <a href="{{ route('product.index', ['category' => $category]) }}" class="btn btn-info"><i
                                        class="fas fa-eye"></i>{{ __('Products') }}</a>
                                @can('management.content')
                                    <a href="{{ route('category.edit', $category) }}" class="btn btn-primary"><i
                                            class="fas fa-pen"></i></a>
                                    <form action="{{ route('category.destroy', $category) }}" method="POST"
                                        class="d-inline-block" onsubmit="return confirm('{{ __('Are you sure?') }}');">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-danger">
                                            <i class="fas fa-trash-alt"></i>
                                        </button>
                                    </form>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
</x-app-layout>