routes/web.php
<?php

use App\Http\Controllers\CardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->name('dashboard');

Route::resource('user', UserController::class)->middleware(['permission:management.user']);

Route::resource('category', CategoryController::class);
Route::resource('product', ProductController::class);


//CART
Route::get('/card/index', [CardController::class, 'index'])->name('cart');
Route::get('/addtocard/{product}', [CardController::class, 'addToCard'])->middleware(['auth'])->name('addToCard');
Route::get('/removefromcard/{product}', [CardController::class, 'removeFromCard'])->middleware(['auth'])->name('removeFromCard');


Route::get('/mediadelete/{media?}', function (Media $media) {
    $media->delete();
    return redirect()->back();
})->middleware(['permission:management.user'])->name('mediadelete');

require __DIR__ . '/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Laravel\Sanctum\HasApiTokens;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Cache;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'phone',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function scopeSearch(Builder $query, ?string $search = null): Builder
    {
        return $query->when($search, function ($query) use ($search) {
            $query->whereRaw("concat(first_name, ' ', last_name) like '%" . $search . "%' ");
        });
    }

    private function cartKey(): string
    {
        return "CART_{$this->id}";
    }

    public function getCart(): Collection
    {
        return Cache::get($this->cartKey(), Collection::make([]));
    }

    public function setCart(Collection $cart): Collection
    {
        Cache::put($this->cartKey(), $cart);
        return $cart;
    }

    public function addCart(Product $product, int $quantity = 1): Collection
    {
        $items = $this->getCart()->toArray();
        if (!isset($items[$product->id]))
            $items[$product->id] = 0;
        $items[$product->id] += $quantity;
        if ($items[$product->id] <= 0)
            unset($items[$product->id]);
        return $this->setCart(Collection::make($items));
    }

    public function removeCart(Product $product): Collection
    {
        $items = $this->getCart()->toArray();
        if (isset($items[$product->id]))
            unset($items[$product->id]);
        return $this->setCart(Collection::make($items));
    }

    public function itemsCart(): Collection
    {
        $items = $this->getCart();
        $products = Product::whereIn('id', $items->keys())->get()->keyBy('id');

        return $items->map(function ($quantity, $productId) use ($products) {
            return (object) [
                'product' => $products[$productId] ?? null,
                'quantity' => $quantity,
            ];
        });
    }
    public function itemCount(): string
    {
        $items = $this->getCart()->toArray();
        $quantity = 0;
        foreach ($items as $key => $value) {
            $quantity += $value;
        }

        return $quantity;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Http\Request;

use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $search = $request->get('search');
        $users =  User::search($search)->paginate()->appends($search);

        return view('user.index', compact('search', 'users'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $roles = Role::all();
        return view('user.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
        $data = $request->validated();
        $user->update($data);
        $user->syncRoles($data['roles'] ?? []);
        return redirect()->route('user.index')->with('success', __('User Updated Successfuly'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('user.index')->with('success', __('User Deleted Successfuly'));
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/user/edit.blade.php
@php($title = $user->exists ? __('Edit User') : __('New User'))
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ $title }}
        </h2>
    </x-slot>

    <form method="post" enctype="multipart/form-data"
        action="{{ $user->exists ? route('user.update', $user) : route('user.store') }}">
        @csrf
        @if ($user->exists)
            @method('PUT')
        @endif
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="first_name">{{ __('First Name') }}</label>
                            <input id="first_name" type="text"
                                class="form-control @error('first_name') is-invalid @enderror" name="first_name"
                                value="{{ $user->first_name }}" required autocomplete="name" autofocus>

                            @error('first_name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="last_name">{{ __('Last Name') }}</label>
                            <input id="last_name" type="text"
                                class="form-control @error('last_name') is-invalid @enderror" name="last_name"
                                value="{{ $user->last_name }}" required autocomplete="name" autofocus>

                            @error('last_name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="phone">{{ __('Phone') }}</label>
                            <input id="phone" type="text"
                                class="form-control @error('phone') is-invalid @enderror" name="phone"
                                value="{{ $user->phone }}" required autocomplete="name" autofocus>

                            @error('phone')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="email">{{ __('E-mail') }}</label>
                            <input id="email" type="text"
                                class="form-control @error('email') is-invalid @enderror" name="email"
                                value="{{ $user->email }}" required autocomplete="name" autofocus>

                            @error('email')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="roles">{{ __('Roles') }}</label>
                            <select class="form-control @error('roles') is-invalid @enderror" id="roles"
                                name="roles[]" multiple>
                                @foreach ($roles as $role)
                                    <option value="{{ $role->id }}"
                                        {{ $user->roles->contains($role) ? 'selected' : '' }}>
                                        {{ $role->name }}
                                    </option>
                                @endforeach
                            </select>
                            @error('roles')
                                <span class="invalid-feedback" user="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i>
                    {{ __('Save') }}
                </button>
            </div>
        </div>
    </form>
</x-app-layout>

resources/views/user/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4   font-weight-bold">
            {{ __('Users') }}
        </h2>
    </x-slot>

    <form>
        <div class="card">
            <div class="card-body">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">{{ __('Search') }}</span>
                        </div>
                        <input type="text" class="form-control" placeholder="{{ __('Search') }}" name="search"
                            value="{{ $search }}">
                        <div class="input-group-append">
                            <button type="submit" class="btn btn-outline-secondary">
                                <i class="fas fa-search"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="card">
        <div class="table-responsive">
            <table class="table table-hover">

                <thead class="thead-dark">
                    <tr>
                        <th scope="col">{{ __('First Name') }}</th>
                        <th scope="col">{{ __('Last Name') }}</th>
                        <th scope="col">{{ __('Phone') }}</th>
                        <th scope="col">{{ __('E-mail') }}</th>
                        <th scope="col">{{ __('Role(s)') }}</th>
                        <th scope="col">{{ __('Actions') }}</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($users as $user)
                        <tr>
                            <td>{{ $user->first_name }}</td>
                            <td>{{ $user->last_name }}</td>
                            <td>{{ $user->phone }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ $user->getRoleNames() }}</td>
                            <td>
                                <a href="{{ route('user.edit', $user) }}" class="btn btn-primary"><i
                                        class="fas fa-pen"></i></a>

                                <form action="{{ route('user.destroy', $user) }}" method="POST" class="d-inline-block"
                                    onsubmit="return confirm('{{ __('Are you sure?') }}');">
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-danger">
                                        <i class="fas fa-trash-alt"></i>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
</x-app-layout>