routes/web.php
<?php

use App\Http\Controllers\CardController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', function () {
    return view('dashboard');
})->name('dashboard');

Route::resource('user', UserController::class)->middleware(['permission:management.user']);

Route::resource('category', CategoryController::class);
Route::resource('product', ProductController::class);


//CART
Route::get('/card/index', [CardController::class, 'index'])->name('cart');
Route::get('/addtocard/{product}', [CardController::class, 'addToCard'])->middleware(['auth'])->name('addToCard');
Route::get('/removefromcard/{product}', [CardController::class, 'removeFromCard'])->middleware(['auth'])->name('removeFromCard');


Route::get('/mediadelete/{media?}', function (Media $media) {
    $media->delete();
    return redirect()->back();
})->middleware(['permission:management.user'])->name('mediadelete');

require __DIR__ . '/auth.php';

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Panel') }}</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

    <!-- Styles -->
    <link rel="stylesheet" href="{{ mix('css/dashboard.css') }}">

    <!-- Scripts -->
    <script src="{{ mix('js/app.js') }}" defer></script>
    <script src="{{ mix('js/dashboard.js') }}" defer></script>
</head>

<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed font-sans antialiased sidebar-collapse">
    <div class="wrapper">

        @include('layouts.navigation')

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-2">
            <!-- Brand Logo -->
            <a href="{{ url('/') }}" class="brand-link">
                <x-application-logo width="36" class="brand-image" />
                <span class="brand-text font-weight-bolder">{{ config('app.name') }}</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                        data-accordion="false">
                        @include('layouts.sidebar')
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col">
                            <h1>{{ $header }}</h1>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col">
                            @if (session('success'))
                                <div class="alert alert-success">
                                    {{ session('success') }}
                                </div>
                            @endif

                            @if (session('warning'))
                                <div class="alert alert-warning">
                                    {{ session('warning') }}
                                </div>
                            @endif
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            {{ $slot }}
                        </div>

                        @if (isset($aside))
                            <div class="col-lg-3">
                                {{ $aside }}
                            </div>
                        @endif
                    </div>
                </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->

        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b><a href="https://jetstream.laravel.com">Jetstream</a></b>
            </div>
            <strong>Powered by</strong> <a href="https://adminlte.io">AdminLTE</a>
        </footer>
    </div>

    @stack('scripts')
</body>

</html>

resources/views/layouts/front.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{{ $title }} - {{ config('app.name') }}</title>
    <link rel="icon" type="image/x-icon" href="{{ asset('assets/favicon.ico') }}" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900"
        rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
        rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{{ asset('theme/css/styles.css') }}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="#page-top">Firma Adı</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span
                    class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>

                </ul>
            </div>
        </div>
    </nav>
    <!-- Header-->
    <header class="masthead text-center text-white" id="page-top"
        style="background-image: url({{ asset('/storage/' . $entryImg) }})">
        <div class="masthead-content">
            <div class="container px-3">
                <h1 class="masthead-heading mb-0" style="color:{{ $entryTextColor }}"> {{ $entryText }}</h1>
                <h2 class="masthead-subheading mb-0" style="color:{{ $entrySubColor }}">{{ $entrySubText }}</h2>
                <a class="btn btn-primary btn-xl rounded-pill mt-5" href="#scroll">{{ $entryButtonText }}</a>
            </div>
        </div>
    </header>
    {{ $slot }}
    <!-- Footer-->
    <footer class="py-5 bg-black">
        <div class="container px-5">
            <p class="m-0 text-center text-white small">{{ $copyright }}</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{{ asset('js/scripts.js') }}"></script>
</body>

</html>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Styles -->
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">

        <!-- Scripts -->
        <script src="{{ asset('js/app.js') }}" defer></script>
    </head>
    <body class="font-sans antialiased bg-light">
        {{ $slot }}
    </body>
</html>

resources/views/layouts/navigation.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>

        <x-nav-link href="{{ url('/') }}">
            <i class="fas fa-home"></i> {{ __('Home') }}
        </x-nav-link>

        {{-- <x-nav-link href="{{ route('admin.dashboard') }}" :active="request()->routeIs('admin.dashboard')">
            <i class="fas fa-desktop"></i> {{ __('Dashboard') }}
        </x-nav-link> --}}
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <!-- Authentication Links -->
        @auth
            <x-nav-link href="{{ route('cart') }}">
                <i class="fas fa-shopping-cart"></i> {{ __('Card') . '(' . Auth::user()->itemCount() . ')' }}
            </x-nav-link>

            <x-dropdown id="navbarDropdown" class="user-menu">
                <x-slot name="trigger">
                    <span class="d-none d-md-inline">{{ Auth::user()->first_name . ' ' . Auth::user()->last_name }}</span>
                </x-slot>

                <x-slot name="content">
                    <!-- Authentication -->
                    <form method="POST" id="logout-form" action="{{ route('logout') }}">
                        @csrf
                        <x-dropdown-link href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                                            document.getElementById('logout-form').submit();">
                            {{ __('Log Out') }}
                        </x-dropdown-link>
                    </form>
                </x-slot>
            </x-dropdown>
        @else
            <x-nav-link href="{{ route('login') }}">
                <i class="fas fa-shopping-cart"></i> {{ __('Card') }}
            </x-nav-link>

            <a href="{{ route('login') }}" class="text-muted">Log in</a>

            @if (Route::has('register'))
                <a href="{{ route('register') }}" class="ms-4 text-muted">Register</a>
            @endif
        @endauth
    </ul>
</nav>
<!-- /.navbar -->

resources/views/layouts/sidebar.blade.php
<x-side-link href="{{ route('dashboard') }}" icon="fas fa-desktop" :active="request()->routeIs('dashboard')">
    {{ __('Dashboard') }}
</x-side-link>

<x-side-link href="{{ route('category.index') }}" icon="fas fa-layer-group" :active="request()->routeIs('category.*')">
    {{ __('Categories') }}
</x-side-link>
<x-side-link href="{{ route('product.index') }}" icon="fas fa-boxes" :active="request()->routeIs('product.*')">
    {{ __('Products') }}
</x-side-link>

@auth
    @if (auth()->user()->hasAnyPermission(['management.user']))
        <x-side-accordion :title="__('Settings')" icon="fas fa-cogs" :active="request()->routeIs(['user.*'])">

            <x-side-link href="{{ route('user.index') }}" icon="fas fa-users" :active="request()->routeIs('user.*')">
                {{ __('Users') }}
            </x-side-link>
        </x-side-accordion>
    @endif
@endauth